import {
  Arrival1,
  Arrival11,
  Arrival2,
  Arrival22,
  Arrival3,
  Arrival33,
  Arrival4,
  Arrival44,
  Banner1,
  Banner2,
  Banner3,
  Blog1,
  Blog2,
  Blog3,
  Seller1,
  Seller11,
  Seller2,
  Seller22,
  Seller3,
  Seller33,
  Seller4,
  Seller44,
  Seller5,
  Seller55,
} from "./helper";

export const bannerItems = [
  {
    id: "b1",
    imgSrc: Banner1,
    title1: "Inspired By",
    title2: "Nature",
    btnText: "Shop Collection",
  },

  {
    id: "b2",
    imgSrc: Banner2,
    title1: "Inspired By",
    title2: "Nature",
    btnText: "Shop Collection",
  },

  {
    id: "b3",
    imgSrc: Banner3,
    title1: "Inspired By",
    title2: "Nature",
    btnText: "Shop Collection",
  },
];

export const blogItems = [
  {
    id: "b1",
    imgSrc: Blog1,
    badge: "Sep 29, 2022",
    title: "So isn’t land signs greater void face",
    description:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deserunt vitae error placeat molestiae...",
  },
  {
    id: "b2",
    imgSrc: Blog2,
    badge: "Dec 01, 2022",
    title: "Sea good every which said first divide",
    description:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deserunt vitae error placeat molestiae...",
  },
  {
    id: "b3",
    imgSrc: Blog3,
    badge: "Dec 09, 2022",
    title: "The morning let you created every day.",
    description:
      "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deserunt vitae error placeat molestiae...",
  },
];

export const newArrivalItems = [
  {
    id: "na1",
    imgSrc1: Arrival1,
    imgSrc11: Arrival11,
    badgeText: "SALE",
    category: "Kids",
    title: "Hiking Boots",
    price: "",
    priceRed: "44.00",
    priceCrossed: "77.00",
  },
  {
    id: "na2",
    imgSrc1: Arrival2,
    imgSrc11: Arrival22,
    badgeText: "HOT",
    category: "Bags",
    title: "Cross Body Mini Bag",
    price: "40.00",
    priceRed: "",
    priceCrossed: "",
  },
  {
    id: "na3",
    imgSrc1: Arrival3,
    imgSrc11: Arrival33,
    badgeText: "SALE",
    category: "Kids",
    title: "Travel Trifold Wallet",
    price: "",
    priceRed: "129.00",
    priceCrossed: "157.00",
  },
  {
    id: "na4",
    imgSrc1: Arrival4,
    imgSrc11: Arrival44,
    badgeText: "HOT",
    category: "T-Shirt",
    title: "Wide Cotton Tunic",
    price: "250.00",
    priceRed: "",
    priceCrossed: "",
  },
  {
    id: "na5",
    imgSrc1: Arrival2,
    imgSrc11: Arrival22,
    badgeText: "HOT",
    category: "Boots",
    title: "Gina Dress Sandals",
    price: "79.00",
    priceRed: "",
    priceCrossed: "",
  },
];

export const topSellerItems = [
  {
    id: "ts1",
    imgSrc1: Seller1,
    imgSrc11: Seller11,
    badgeText: "SALE",
    category: "Boots",
    title: "Clarks Women’s Step Cali",
    price: "45.00",
    priceRed: "",
    priceCrossed: "",
  },
  {
    id: "ts2",
    imgSrc1: Seller2,
    imgSrc11: Seller22,
    badgeText: "HOT",
    category: "Bags",
    title: "Geometric print Scarf",
    price: "23.00",
    priceRed: "3.00",
    priceCrossed: "50.00",
  },
  {
    id: "ts3",
    imgSrc1: Seller3,
    imgSrc11: Seller33,
    badgeText: "SALE",
    category: "Bags",
    title: "Cross Body Mini Bag",
    price: "40.00",
    priceRed: "",
    priceCrossed: "",
  },
  {
    id: "ts4",
    imgSrc1: Seller4,
    imgSrc11: Seller44,
    badgeText: "SALE",
    category: "Mens",
    title: "Yellow Reserved Hoodie",
    price: "123.00",
    priceRed: "",
    priceCrossed: "200.00",
  },
  {
    id: "ts5",
    imgSrc1: Seller5,
    imgSrc11: Seller55,
    badgeText: "SALE",
    category: "Dresses",
    title: "Tarot Garden Dress",
    price: "129.00",
    priceRed: "",
    priceCrossed: "",
  },
];
